# MCP Server Template Configuration

# Server configuration
server:
  name: "my-mcp-server"
  transport: "streamable-http"
  host: "127.0.0.1"
  port: 8000

# Cache configuration
cache:
  query_cache_size: 1000
  query_cache_ttl: 300        # 5 minutes
  schema_cache_size: 100
  schema_cache_ttl: 3600      # 1 hour
  metadata_cache_size: 500
  metadata_cache_ttl: 1800    # 30 minutes

# Data sources configuration
datasources:
  # MySQL data source
  mysql:
    enabled: true
    host: "localhost"
    port: 3306
    user: "root"
    password: "password"
    database: "my_database"
    charset: "utf8mb4"
    max_connections: 10
    connect_timeout: 10
    schema_cache_ttl: 3600
    query_cache_ttl: 300
    max_query_limit: 1000

  # REST API data source
  rest_api:
    enabled: true
    base_url: "https://api.example.com"
    auth_type: "bearer"        # none, bearer, basic, api_key
    auth_token: "your_token"
    timeout: 30
    rate_limit: 100            # requests per minute
    retry_attempts: 3
    schema_endpoint: "/schema"
    discovery_endpoint: "/discovery"
    schema_cache_ttl: 3600
    query_cache_ttl: 300
    max_query_limit: 1000

  # GitHub API example
  github:
    enabled: false
    base_url: "https://api.github.com"
    auth_type: "bearer"
    auth_token: "${GITHUB_TOKEN}"
    timeout: 30
    rate_limit: 60
    retry_attempts: 3
    schema_cache_ttl: 3600
    query_cache_ttl: 300
    max_query_limit: 1000

# Client configuration
client:
  server_url: "http://127.0.0.1:8000/mcp"
  cors_origins: 
    - "http://localhost:3000"
    - "http://localhost:8080"
  timeout: 30

# LLM configuration (optional)
llm:
  enabled: false
  provider: "nail"             # nail, openai, anthropic, etc.
  model_id: "claude-3.5"
  temperature: 0.2
  max_tokens: 600
  api_key: "${LLM_API_KEY}"

# Logging configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "mcp_server.log"
